fix many problems

diff --git a/vagrant_support/bmo-configured b/vagrant_support/bmo-configured
--- a/vagrant_support/bmo-configured
+++ b/vagrant_support/bmo-configured
@@ -1,12 +1,35 @@
 #!/bin/bash
 
-
-[[ -f /vagrant/localconfig ]] || exit 1
-[[ -f /vagrant/data/params ]] || exit 1
-grep "'urlbase' => ''" /vagrant/data/params && exit 1
-
-if stat -c %G /vagrant/data/params | grep vagrant; then
+if [[ ! -f /vagrant/localconfig ]]; then
+    echo "missing localconfig"
     exit 1
 fi
+
+if [[ ! -f /vagrant/data/params ]]; then
+    echo "missing data/params"
+    exit 1
+fi
+
+if grep -q "'urlbase' => ''" /vagrant/data/params; then
+    echo "urlbase not configured"
+    exit 1;
+fi
+
+if grep -q '$db_host.*localhost' /vagrant/localconfig; then
+    echo "\$db_host not configured"
+    exit 1
+fi
+
+for file in /vagrant/data/params /vagrant/index.cgi; do
+    info="$(stat -c %U.%G "$file")"
+
+    if [[ $info != "root.apache" ]]; then
+        echo "wrong file owner: $info $file"
+        exit 1
+    fi
+done
+
+cd /vagrant
+sudo -u apache perl -T index.cgi &>/dev/null || exit 1
 
 exit 0
